# Generated by Django 5.2.9 on 2025-12-25 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('lesson_time', models.TimeField(verbose_name='Время начала пары')),
                ('lesson_type', models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('SRSP', 'СРСП')], max_length=10, verbose_name='Тип занятия')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Балл (1-12)')),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Присутствовал'), ('ABSENT_ILLNESS', 'НБ-Болезнь'), ('ABSENT_VALID', 'НБ-Уважительная'), ('ABSENT_INVALID', 'НБ-Неуважительная')], default='PRESENT', max_length=20, verbose_name='Статус посещения')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to='accounts.teacher', verbose_name='Создал')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_entries', to='accounts.teacher', verbose_name='Изменил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='schedule.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Записи в журнале',
                'ordering': ['-lesson_date', 'lesson_time', 'student__user__last_name'],
                'unique_together': {('student', 'subject', 'lesson_date', 'lesson_time')},
            },
        ),
        migrations.CreateModel(
            name='JournalChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('old_grade', models.IntegerField(blank=True, null=True, verbose_name='Старый балл')),
                ('old_attendance', models.CharField(blank=True, max_length=20, verbose_name='Старая посещаемость')),
                ('new_grade', models.IntegerField(blank=True, null=True, verbose_name='Новый балл')),
                ('new_attendance', models.CharField(blank=True, max_length=20, verbose_name='Новая посещаемость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher', verbose_name='Кто изменил')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='journal.journalentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Лог изменений',
                'verbose_name_plural': 'Логи изменений',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_gpa', models.FloatField(default=0.0, verbose_name='Общий средний балл')),
                ('group_rank', models.IntegerField(default=0, verbose_name='Рейтинг в группе')),
                ('attendance_percentage', models.FloatField(default=0.0, verbose_name='Процент посещаемости')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='Всего занятий')),
                ('attended_lessons', models.IntegerField(default=0, verbose_name='Посещено занятий')),
                ('subjects_data', models.JSONField(default=dict, verbose_name='Данные по предметам')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='accounts.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Статистика студента',
                'verbose_name_plural': 'Статистика студентов',
            },
        ),
    ]
