# Generated by Django 5.2.9 on 2025-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatistics',
            name='absent_illness',
            field=models.IntegerField(default=0, verbose_name='НБ-Болезнь'),
        ),
        migrations.AddField(
            model_name='studentstatistics',
            name='absent_invalid',
            field=models.IntegerField(default=0, verbose_name='НБ-Неуважительная'),
        ),
        migrations.AddField(
            model_name='studentstatistics',
            name='absent_valid',
            field=models.IntegerField(default=0, verbose_name='НБ-Уважительная'),
        ),
        migrations.AddField(
            model_name='studentstatistics',
            name='total_absent',
            field=models.IntegerField(default=0, verbose_name='Всего прогулов'),
        ),
    ]
