# Generated by Django 5.2.9 on 2026-01-07 05:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Курс')),
                ('academic_year', models.IntegerField(verbose_name='Год обучения')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', 'Студент'), ('TEACHER', 'Преподаватель'), ('DEAN', 'Декан')], default='STUDENT', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение офиса')),
                ('reception_hours', models.CharField(blank=True, max_length=200, verbose_name='Часы приема')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dean_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Декан',
                'verbose_name_plural': 'Деканы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Номер зачетки')),
                ('course', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Курс')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('admission_year', models.IntegerField(verbose_name='Год поступления')),
                ('financing_type', models.CharField(choices=[('BUDGET', 'Бюджет'), ('CONTRACT', 'Контракт')], max_length=10, verbose_name='Тип финансирования')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('ACADEMIC_LEAVE', 'Академический отпуск'), ('EXPELLED', 'Отчислен')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('education_type', models.CharField(choices=[('FULL_TIME', 'Очное'), ('PART_TIME', 'Заочное'), ('EVENING', 'Вечернее')], default='FULL_TIME', max_length=10, verbose_name='Вид обучения')),
                ('education_language', models.CharField(choices=[('TJ', 'Таджикский'), ('RU', 'Русский'), ('EN', 'Английский')], max_length=2, verbose_name='Язык обучения')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('passport_series', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('registration_address', models.TextField(verbose_name='Адрес регистрации')),
                ('residence_address', models.TextField(verbose_name='Адрес проживания')),
                ('sponsor_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО спонсора')),
                ('sponsor_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон спонсора')),
                ('sponsor_relation', models.CharField(blank=True, max_length=50, verbose_name='Отношение спонсора')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.group', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['course', 'group', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('from_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='accounts.group')),
                ('to_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='accounts.group')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='accounts.student')),
            ],
            options={
                'verbose_name': 'История переводов',
                'verbose_name_plural': 'История переводов',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('NONE', 'Без степени'), ('CANDIDATE', 'Кандидат наук'), ('DOCTOR', 'Доктор наук')], default='NONE', max_length=20, verbose_name='Ученая степень')),
                ('title', models.CharField(choices=[('NONE', 'Без звания'), ('ASSISTANT', 'Ассистент'), ('SENIOR_TEACHER', 'Старший преподаватель'), ('DOCENT', 'Доцент'), ('PROFESSOR', 'Профессор')], default='NONE', max_length=20, verbose_name='Ученое звание')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('research_interests', models.TextField(blank=True, verbose_name='Научные интересы')),
                ('consultation_hours', models.CharField(blank=True, max_length=200, verbose_name='Часы консультаций')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['user__last_name'],
            },
        ),
    ]
