# Generated by Django 5.2.9 on 2026-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('TEACHER', 'Преподаватель'), ('DEAN', 'Декан')], default='STUDENT', max_length=10),
        ),
    ]
