# Generated by Django 5.2.9 on 2026-01-07 05:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер кабинета')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('capacity', models.IntegerField(default=30, verbose_name='Вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название семестра')),
                ('number', models.IntegerField(choices=[(1, '1 семестр'), (2, '2 семестр')], verbose_name='Номер семестра')),
                ('shift', models.CharField(choices=[('MORNING', 'Утреннее (08:00-12:50)'), ('AFTERNOON', 'Дневное (13:00-18:50)')], default='AFTERNOON', max_length=10, verbose_name='Смена')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный семестр')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)], verbose_name='Кредиты (часы в неделю)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('SRSP', 'СРСП')], max_length=10, verbose_name='Тип занятия')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='schedule.classroom', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='accounts.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='accounts.teacher', verbose_name='Преподаватель')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='schedule.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='schedule.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField(verbose_name='Дата исключения')),
                ('exception_type', models.CharField(choices=[('CANCEL', 'Отмена'), ('RESCHEDULE', 'Перенос')], max_length=20, verbose_name='Тип исключения')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Новое время начала')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Новое время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('new_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.classroom', verbose_name='Новая аудитория')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedule.scheduleslot', verbose_name='Слот расписания')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'ordering': ['-exception_date'],
                'unique_together': {('schedule_slot', 'exception_date')},
            },
        ),
        migrations.CreateModel(
            name='AcademicWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Номер недели')),
                ('start_date', models.DateField(verbose_name='Начало недели')),
                ('end_date', models.DateField(verbose_name='Конец недели')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая неделя')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='schedule.semester', verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'Учебная неделя',
                'verbose_name_plural': 'Учебные недели',
                'ordering': ['semester', 'week_number'],
                'unique_together': {('semester', 'week_number')},
            },
        ),
    ]
