# Generated by Django 5.2.9 on 2026-01-07 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hours_per_semester',
            field=models.IntegerField(default=0, help_text='Общее количество часов за весь семестр', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Часов за семестр'),
        ),
    ]
